name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env: 
  DOCKER_NAME: blkhrt225
  DOCKER_TOKEN: ef55a328-fa2a-4b7b-b1f0-a560e8fea288
  IMAGE: blkhrt225/docker-test
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with: 
        username: ${{env.DOCKER_NAME}}
        password: ${{env.DOCKER_TOKEN}}
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{env.NAME}}:$GITHUB_SHA
    - name: Push the Docker Image
      run: docker push ${{env.NAME}}:$GITHUB_SHA
